import type { Metadata } from "next";
import { Geist, Geist_Mono, VT323, Pixelify_Sans, Silkscreen } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vt323 = VT323({
  variable: "--font-vt323",
  subsets: ["latin"],
  weight: "400",
});

const pixelifySans = Pixelify_Sans({
  variable: "--font-pixelify",
  subsets: ["latin"],
});

const silkscreen = Silkscreen({
  variable: "--font-silkscreen",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${vt323.variable} ${pixelifySans.variable} ${silkscreen.variable} h-full antialiased`}
    >
      {/* inline night bg in the SSR'd HTML → first paint is dark even before the CSS chunk loads
          (kills the dirt-yellow reload flash; CSS in globals.css is the backup) */}
      <body className="min-h-full flex flex-col" style={{ background: "#0e0c30" }}>
        {children}
      </body>
    </html>
  );
}
